name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  get_it: ^8.0.2
  injectable: ^2.5.0
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5 
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: 
